### ISSUE TITLE
Skapa ett internt interface för datahämtning

### ISSUE THREAD

**Issue by joaxcar** [joaxcar/bookbook#10]
Skapa ett mellanliggande lager för data. En "search"-fil som kopplar views mot API-förfrågningar.
Strukturen ska vara:
view ber om sökning av "search" -> "search" gör sökning mot API(tex google) -> googleAPI söker och monterar om datan

**Comment by joaxcar** [comment]
API result:
  {
    totalItems: "",
    items: [{
       title: "",
       author: "",
       isbn:[],
       description: "",
       yearPublished: "",
       image: "",
     },]
   }

Stored data:
[
  {
    book: BOOK,
    starRating: "",
    review: "",
    lable: [],
  },
]

**Comment by joaxcar** [comment]
I search ska finnas:

sökning med namn, titel eller isbn eller flera. Samt antal resultat och offset

**Comment by jokrau** [comment]
anything left here? I'm in a resolve issues kinda mood
